### ISSUE TITLE
Basic platformer mechanics

### ISSUE THREAD

**Issue by quigley-c** [codeandkey/boom#1]
The game needs basic movement and jumping mechanics to function properly as a game.

**Comment by codeandkey** [comment]
It might be worth it to start out with a fixed tile-based map instead of block-based; we want to have rock solid collisions and movement as early as possible.

**Comment by quigley-c** [comment]
To start we'll need a collision system, which we have as issue #5 already. Then we can move on to things like player movement and interactions.

**Comment by codeandkey** [comment]
I think we might be able to consider this closed now.

**Comment by quigley-c** [comment]
Yes, this issue is no longer needed.
