### ISSUE TITLE
Options considerations

### ISSUE THREAD

**Issue by codeandkey** [codeandkey/boom#114]
The game's options currently work but feel very minimal. I think it may be beneficial to remove the options menu entirely and default to using the native video mode on the primary monitor (in fullscreen). The game can then perform its own scaling in software so users won't need to worry about configuration. I think having vsync always on would also be a good idea.

**Comment by codeandkey** [comment]
As a note, removing the options menu and reverting to a controlled video mode would fix #103.

**Comment by quigley-c** [comment]
This is an interesting idea @codeandkey. At the very least we should have an option to toggle fullscreen, but this can be bound to a key if we decide to take this route.

Is there any reason to remove the options menu as it is? I think we could get away with not changing it at all...

**Comment by codeandkey** [comment]
After playing through some more I agree options are fine as is. With the GUI incoming we will be able to make the game more resolution-independent anyway so I think this can be closed for now.
