### ISSUE TITLE
Explosion effects

### ISSUE THREAD

**Issue by codeandkey** [codeandkey/boom#19]
The explosion object currently has a placeholder for drawing, we should design some graphical effects for it.

An explosion sprite is a good start, and we could also add sparks / particle effects as well.

**Comment by quigley-c** [comment]
Do we prefer sprites for the explosion effect? We could potentially generate an intense light to go along with the screen shaking effects. Thoughts?

**Comment by quigley-c** [comment]
@codeandkey

**Comment by codeandkey** [comment]
I think both a sprite and some lighting/smoke effects would be good. Maybe we can throw a bunch of effects at it and see what sticks. Sorry for missing the last comment!

**Comment by codeandkey** [comment]
Explosions have since been added to the game.
