### ISSUE TITLE
No main menu

### ISSUE THREAD

**Issue by quigley-c** [codeandkey/boom#30]
# Main Menu
We should add a main menu to the game where players can see options like "new game" or "options".

**Comment by quigley-c** [comment]
How should this be implemented? Should we use fonts to place clickable buttons on the screen? Should we have some drawn assets as well?

**Comment by codeandkey** [comment]
I think it will be best if we unify most/all of the game's GUI into a new subsystem. Having reusable buttons and stuff will allow for easily adding menus in the future.
