### ISSUE TITLE
Dialog events / shattering dialog boxes

### ISSUE THREAD

**Issue by quigley-c** [codeandkey/boom#36]
# Dialog
Currently there isn't any way of interacting with NPC's. We should have some text-based. Dialogs should shatter when NPC's are killed during conversation.

## NPC interaction
The idea behind this is to use the existing `interact` event in the character component to allow the player (and other NPCs) to interact with other characters. We should have some sort of check to have NPCs say different things depending on who is talking to them (player, other npcs). The beauty of the character component is that the interact event can be used by any character, that means the player and NPCs already have a method of interaction, we just have to make npcs intractable.

## Shattering textboxes
This is a genius idea and I think should be one of the highlighted points of the game, really makes it unique compared to other games in the genre. 

Textboxes should shatter when the NPC speaking is killed. It seems like this can be accomplished by making the text boxes objects, though I haven't experimented with this myself. If we decide to take a more traditional approach to the visual design of textboxes, the speaking NPC will have their portrait displayed at the top along with the text, this should shatter as well. If we decide to make the boxes appear above the NPCs as they speak this won't be a problem. The design choice we make will be important as the visuals along with dialog will influence how the game feels and how effective this mechanic will be.

**Comment by quigley-c** [comment]
Personally, I think we should have more traditional text: at the top of the screen with a portrait. We won't take control away from the player but it creates a familiar feel, which makes the subversion all the more effective.

**Comment by codeandkey** [comment]
I like the sprite! Will this be an enemy?

**Comment by quigley-c** [comment]
@codeandkey I've thought about this quite a bit and I think it would be beneficial to have both bubble text boxes (as seen in live) and a more traditional UI dialog box that appears at the top or bottom of the screen for important events (story events, quests, etc)

**Comment by codeandkey** [comment]
Will implement this today.

**Comment by quigley-c** [comment]
Merged.
