### ISSUE TITLE
No HUD

### ISSUE THREAD

**Issue by codeandkey** [codeandkey/boom#51]
The game could benefit from some form of HUD -- perhaps one that shows player health, grenades or abilities.

**Comment by quigley-c** [comment]
What kind of HUD should we go for? My stance on this is to take a less-is-more approach and attempt to communicate important details in as many clever ways as possible to keep hud minimal.

**Comment by quigley-c** [comment]
for example: having the player and/or enemies have visual tells to communicate health

**Comment by codeandkey** [comment]
I think a minimal HUD is a good approach. In fact we may not need a HUD at all. Then the GUI subsystem will be entirely for menus and we can move dialog to the object model.

**Comment by quigley-c** [comment]
closed
