### ISSUE TITLE
Foreground fade

### ISSUE THREAD

**Issue by quigley-c** [codeandkey/boom#83]
# What's the issue?
In order for secrets and other map-related unveiling of areas to become effective (and not look wonky like they do right now) we should make a foreground layer for tiles that will fade away when the player touches a trigger. Additionally we should make these tiles appear above the player when not faded out as it will create a more interesting perspective, appearing as though the player is actually discovering something that was previously hidden.

## Foreground tile layer
Currently there is a foreground tile layer in the maps, though it is merely a scenery layer right now. The tiles in the layer still appear behind the player and other objects and there is no way to have them disappear when the player touches a trigger. These are the primary features we are aiming for with this feature.

## Desired result
The goal with this feature is to create the feeling of discovery associated with revealing more information to the player. To do this we need the features listed above and to cleverly place triggers that show the player things as they discover them. Found a strange looking texture? When you walk behind it, it shows you a hidden path!

**Comment by codeandkey** [comment]
Closed by #86
