### ISSUE TITLE
Continuous Death Animation

### ISSUE THREAD

**Issue by Mitchello457** [codeandkey/boom#99]
**DEBUG   | pcall() failed: object_types/player.lua:108: attempt to index local 'loc' (a nil value)**

After I murdered myself with a grenade, the death animation just kept zooming in on my decapitated head and never stopped to respawn me. The error is listed above.

**Comment by Mitchello457** [comment]
It seems like the issue is that if the player does not save the game prior to dying, there is no *save_location* set to *loc*. Therefore *loc.map_name* and *loc.spawn_name* were both empty.

**Comment by quigley-c** [comment]
Closed as of #111
